spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tKmrYoZ2C8mLPL9gsxA
      secret-key: LhzwR1tidY5LPcfEkIWJdUcGtYHYgF
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: java-gulimall-hello

  application:
    name: gulimall-third-party

server:
  port: 30000
